sudo: true
dist: trusty


jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - ls -ltr ./themes/docdock
      - docker build -t commonplace .
      - docker images
      - docker tag commonplace $DOCKER_USERNAME/commonplace
      - docker push $DOCKER_USERNAME/commonplace
