apiVersion: apps/v1
kind: Deployment
metadata:
  name: emv-commonplace-nginx-deployment
  labels:
    app: emv-commonplace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emv-commonplace
  template:
    metadata:
      labels:
        app: emv-commonplace
    spec:
      containers:
      - name: emv-commonplace
        image: vielmetti/emv-commonplace:latest
        ports:
        - containerPort: 80
