baseURL = "https://vielmetti.github.io/commonplace/"
languageCode = "en-us"
title = "Commonplace"
theme = "docdock"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true
